version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "python mysite/manage.py migrate && python mysite/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
